using System.Collections.Immutable;
using System.Reflection;
using System.Text;
using System.Text.Json;
using Rlab.Domain.Contracts;
using Rlab.Domain.Generated;
using Rlab.Domain.Metadata;
using Rlab.Domain.Run;
using Rlab.Domain.Workspace;
using Rlab.Infrastructure.Queries;

namespace Rlab.Infrastructure.Contracts;

public interface IRlabTypeScriptContractExporter
{
    string Export();
}

public sealed class RlabTypeScriptContractExporter : IRlabTypeScriptContractExporter
{
    private static readonly Type[] RootTypes =
    [
        typeof(RlabCommandEnvelope),
        typeof(RlabCommandRequest),
        typeof(RlabCommandResult),
        typeof(RlabCommandResponse),
        typeof(RlabQueryEnvelope),
        typeof(WorkspaceView),
        typeof(ConversationView),
        typeof(ThreadMessageView),
        typeof(ChatMessage),
        typeof(ConversationSummary),
        typeof(ProjectSummary),
        typeof(ComposerDraft),
        typeof(WorkspaceSettings),
        typeof(RunView),
        typeof(RunOutputEvent),
        typeof(WorkspaceThreadResult),
        typeof(ActiveRunsResult)
    ];

    private readonly RlabModelRegistry _registry;
    private readonly Dictionary<Type, string> _typeNames = new();
    private readonly NullabilityInfoContext _nullability = new();

    public RlabTypeScriptContractExporter(RlabModelRegistry registry)
    {
        _registry = registry;
    }

    public string Export()
    {
        var roots = _registry.Models
            .Where(model => model.Kind is RlabModelKind.Command or RlabModelKind.Event or RlabModelKind.Query)
            .Select(model => RlabGeneratedRegistry.ResolveType(model.ClrType))
            .Concat(RootTypes)
            .Distinct()
            .ToArray();

        foreach (var type in roots)
        {
            Collect(type);
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("/* eslint-disable */");
        builder.AppendLine();

        foreach (var type in _typeNames.Keys.OrderBy(GetTypeScriptName, StringComparer.Ordinal))
        {
            EmitType(builder, type);
            builder.AppendLine();
        }

        EmitVersionMap(builder, "rlabCommands", _registry.Commands);
        EmitVersionMap(builder, "rlabEvents", _registry.Events);
        EmitVersionMap(builder, "rlabQueries", _registry.Queries);

        EmitDataMap(builder, "RlabCommandDataByType", _registry.Commands);
        EmitDataMap(builder, "RlabEventDataByType", _registry.Events);
        EmitDataMap(builder, "RlabQueryDataByType", _registry.Queries);

        builder.AppendLine("export type RlabCommandType = keyof typeof rlabCommands;");
        builder.AppendLine("export type RlabEventType = keyof typeof rlabEvents;");
        builder.AppendLine("export type RlabQueryType = keyof typeof rlabQueries;");
        builder.AppendLine();
        builder.AppendLine("export type RlabTypedCommandEnvelope = {");
        builder.AppendLine("  [K in RlabCommandType]: { commandId: string; clientId: string; type: K; version: (typeof rlabCommands)[K]; data: RlabCommandDataByType[K]; correlationId?: string | null; causationId?: string | null; actor?: string | null }");
        builder.AppendLine("}[RlabCommandType];");
        builder.AppendLine();
        builder.AppendLine("export type RlabTypedQueryEnvelope = {");
        builder.AppendLine("  [K in RlabQueryType]: { queryId: string; type: K; version: (typeof rlabQueries)[K]; data: RlabQueryDataByType[K] }");
        builder.AppendLine("}[RlabQueryType];");
        builder.AppendLine();
        builder.AppendLine("export type RlabSseEvent = {");
        builder.AppendLine("  [K in RlabEventType]: { type: K; globalPosition: number; streamPosition: number; streamId: string | null; streamKey: string | null; data: RlabEventDataByType[K]; commandId?: string | null; clientId?: string | null; correlationId?: string | null; causationId?: string | null; actor?: string | null; createdAt: string }");
        builder.AppendLine("}[RlabEventType];");

        return builder.ToString();
    }

    private void EmitType(StringBuilder builder, Type type)
    {
        var properties = GetSerializableProperties(type).ToArray();
        var name = GetTypeScriptName(type);
        if (properties.Length == 0)
        {
            builder.Append("export type ").Append(name).AppendLine(" = Record<string, never>;");
            return;
        }

        builder.Append("export interface ").Append(name).AppendLine(" {");
        foreach (var property in properties)
        {
            var nullability = _nullability.Create(property);
            builder.Append("  ")
                .Append(ToCamelCase(property.Name))
                .Append(": ")
                .Append(ToTypeScriptType(property.PropertyType, nullability))
                .AppendLine(";");
        }

        builder.AppendLine("}");
    }

    private void EmitVersionMap(StringBuilder builder, string name, ImmutableArray<RlabModelDescriptor> descriptors)
    {
        builder.Append("export const ").Append(name).AppendLine(" = {");
        foreach (var descriptor in descriptors.OrderBy(descriptor => descriptor.WireName, StringComparer.Ordinal))
        {
            builder.Append("  \"").Append(descriptor.WireName).Append("\": ").Append(descriptor.Version).AppendLine(",");
        }

        builder.AppendLine("} as const;");
        builder.AppendLine();
    }

    private void EmitDataMap(StringBuilder builder, string name, ImmutableArray<RlabModelDescriptor> descriptors)
    {
        builder.Append("export interface ").Append(name).AppendLine(" {");
        foreach (var descriptor in descriptors.OrderBy(descriptor => descriptor.WireName, StringComparer.Ordinal))
        {
            var type = RlabGeneratedRegistry.ResolveType(descriptor.ClrType);
            builder.Append("  \"").Append(descriptor.WireName).Append("\": ").Append(GetTypeScriptName(type)).AppendLine(";");
        }

        builder.AppendLine("}");
        builder.AppendLine();
    }

    private void Collect(Type type)
    {
        type = UnwrapNullable(type);
        if (IsScalar(type) || type == typeof(JsonElement) || type.IsEnum)
        {
            return;
        }

        if (TryGetDictionaryValueType(type, out var dictionaryValueType))
        {
            Collect(dictionaryValueType);
            return;
        }

        if (TryGetCollectionElementType(type, out var elementType))
        {
            Collect(elementType);
            return;
        }

        if (type.Namespace?.StartsWith("System", StringComparison.Ordinal) == true)
        {
            return;
        }

        _typeNames.TryAdd(type, GetTypeScriptName(type));
        foreach (var property in GetSerializableProperties(type))
        {
            Collect(property.PropertyType);
        }
    }

    private string ToTypeScriptType(Type type, NullabilityInfo? nullability)
    {
        var nullable = nullability?.WriteState == NullabilityState.Nullable || Nullable.GetUnderlyingType(type) is not null;
        var unwrapped = UnwrapNullable(type);
        string result;

        if (unwrapped == typeof(string) || unwrapped == typeof(DateTimeOffset) || unwrapped == typeof(DateTime))
        {
            result = "string";
        }
        else if (unwrapped == typeof(bool))
        {
            result = "boolean";
        }
        else if (IsNumber(unwrapped))
        {
            result = "number";
        }
        else if (unwrapped == typeof(JsonElement))
        {
            result = "unknown";
        }
        else if (TryGetDictionaryValueType(unwrapped, out var dictionaryValueType))
        {
            var valueNullability = nullability?.GenericTypeArguments.Length == 2 ? nullability.GenericTypeArguments[1] : null;
            result = $"Readonly<Record<string, {ToTypeScriptType(dictionaryValueType, valueNullability)}>>";
        }
        else if (TryGetCollectionElementType(unwrapped, out var elementType))
        {
            var elementNullability = nullability?.GenericTypeArguments.Length == 1 ? nullability.GenericTypeArguments[0] : null;
            result = $"ReadonlyArray<{ToTypeScriptType(elementType, elementNullability)}>";
        }
        else
        {
            result = GetTypeScriptName(unwrapped);
        }

        return nullable ? $"{result} | null" : result;
    }

    private static IEnumerable<PropertyInfo> GetSerializableProperties(Type type)
    {
        return type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property.GetMethod is not null && property.GetMethod.IsPublic)
            .Where(property => property.GetIndexParameters().Length == 0)
            .OrderBy(property => property.MetadataToken);
    }

    private static bool TryGetCollectionElementType(Type type, out Type elementType)
    {
        var collection = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IReadOnlyList<>)
            ? type
            : type.GetInterfaces().FirstOrDefault(candidate => candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IReadOnlyList<>));

        if (collection is not null)
        {
            elementType = collection.GetGenericArguments()[0];
            return true;
        }

        elementType = typeof(object);
        return false;
    }

    private static bool TryGetDictionaryValueType(Type type, out Type valueType)
    {
        var dictionary = type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>)
            ? type
            : type.GetInterfaces().FirstOrDefault(candidate => candidate.IsGenericType && candidate.GetGenericTypeDefinition() == typeof(IReadOnlyDictionary<,>));

        if (dictionary is not null && dictionary.GetGenericArguments()[0] == typeof(string))
        {
            valueType = dictionary.GetGenericArguments()[1];
            return true;
        }

        valueType = typeof(object);
        return false;
    }

    private static Type UnwrapNullable(Type type) => Nullable.GetUnderlyingType(type) ?? type;

    private static bool IsScalar(Type type) => type == typeof(string)
        || type == typeof(DateTimeOffset)
        || type == typeof(DateTime)
        || type == typeof(bool)
        || IsNumber(type);

    private static bool IsNumber(Type type) => type == typeof(byte)
        || type == typeof(short)
        || type == typeof(int)
        || type == typeof(long)
        || type == typeof(float)
        || type == typeof(double)
        || type == typeof(decimal);

    private static string GetTypeScriptName(Type type)
    {
        var name = type.Name;
        var tick = name.IndexOf('`', StringComparison.Ordinal);
        return tick >= 0 ? name[..tick] : name;
    }

    private static string ToCamelCase(string value)
    {
        return string.IsNullOrEmpty(value) || char.IsLower(value[0])
            ? value
            : char.ToLowerInvariant(value[0]) + value[1..];
    }
}
