import { describe, expect, it } from "vitest";
import type { ApiHandler } from "../src/server/api-router";
import { createRlabApiRoutes, type RlabApiRouteHandlers } from "../src/server/api-routes";

const noop: ApiHandler = () => undefined;

const handlers: RlabApiRouteHandlers = {
  agentConfig: noop,
  agentInstall: noop,
  agentLimits: noop,
  agents: noop,
  attachments: noop,
  browserAction: noop,
  browserBridgeAction: noop,
  browserBridgeSnapshot: noop,
  browserBridgeSync: noop,
  browserDirty: noop,
  browserEvents: noop,
  browserSession: noop,
  browserSnapshot: noop,
  browserSync: noop,
  cliUpdates: noop,
  folderInfo: noop,
  folderPicker: noop,
  gitCheckout: noop,
  gitCommit: noop,
  gitDiff: noop,
  gitInit: noop,
  gitPush: noop,
  gitStage: noop,
  gitStatus: noop,
  gitTree: noop,
  gitUnstage: noop,
  gitWorktreeCreate: noop,
  gitWorktreeMerge: noop,
  health: noop,
  listDirectories: noop,
  localFile: noop,
  playwrightInstall: noop,
  projectFiles: noop,
  rlabPlugins: noop,
  run: noop,
  runApproval: noop,
  runAttach: noop,
  runCancel: noop,
  runInput: noop,
  runs: noop,
  commands: noop,
  stateEvents: noop,
  stateSnapshot: noop,
  stateThread: noop,
  terminal: noop,
  version: noop,
  voiceConfig: noop,
  voiceTranscribe: noop,
  wakeups: noop,
};

describe("rlab api routes", () => {
  it("keeps the mounted API surface in one server route table", () => {
    expect(createRlabApiRoutes(handlers).map((route) => route.path)).toEqual([
      "/api/health",
      "/api/browser/session",
      "/api/browser/sync",
      "/api/browser/dirty",
      "/api/browser/action",
      "/api/browser/bridge/sync",
      "/api/browser/bridge/action",
      "/api/browser/bridge/snapshot",
      "/api/browser/snapshot",
      "/api/browser/events",
      "/api/commands",
      "/api/state/snapshot",
      "/api/state/thread",
      "/api/state/events",
      "/api/agents",
      "/api/rlab-plugins",
      "/api/agent-config",
      "/api/voice-config",
      "/api/voice/transcribe",
      "/api/agent-install",
      "/api/playwright-install",
      "/api/folder-picker",
      "/api/list-directories",
      "/api/folder-info",
      "/api/project-files",
      "/api/attachments",
      "/api/local-file",
      "/api/version",
      "/api/agent-limits",
      "/api/cli-updates",
      "/api/git-status",
      "/api/git-tree",
      "/api/git-diff",
      "/api/git-stage",
      "/api/git-unstage",
      "/api/git-commit",
      "/api/git-checkout",
      "/api/git-push",
      "/api/git-worktree-create",
      "/api/git-worktree-merge",
      "/api/git-init",
      "/api/terminal",
      "/api/runs",
      "/api/wakeups",
      "/api/run-attach",
      "/api/run",
      "/api/run-approval",
      "/api/run-cancel",
      "/api/run-input",
    ]);
  });
});
